### ISSUE TITLE
Intentionally offline slaves should be distinguishable

### ISSUE THREAD

**Issue by josephharrington** [box-labs/ClusterRunner-Dashboard#4]
It should be obvious from looking at the slave monitor dashboard if a slave has been explicitly shutdown or if it went offline due to an error. This should be easy via the `is_in_shutdown_mode` field of the slave api response.

**Comment by tjlee0909** [comment]
Closed by https://github.com/josephharrington/ClusterRunner-Dashboard/pull/7 - slaves explicitly shutdown no longer show on the dashboard now.
